### ISSUE TITLE
ReSharper 2016.3 Support

### ISSUE THREAD

**Issue by atzimler** [JetBrains/resharper-cyclomatic-complexity#10]
Hi,

Is there any plan to release 2016.3 installer for this package?
If not, could you provide a quick start on how to compile the project for that version?

Thanks,
Regards,
Attila

**Comment by citizenmatt** [comment]
Yes, I plan to get it sorted on Monday. It'll should just be a case of updating the JetBrains.ReSharper.SDK package, and updating the Wave dependency in the nuspec file to 7.0

**Comment by atzimler** [comment]
Thank you, your extension is really useful for reviewing and improving code quality.

**Comment by citizenmatt** [comment]
Of course, it's never as easy as you hope. I haven't forgotten this, though...

**Comment by citizenmatt** [comment]
Right. Sorry about that, issues with the tests (still not fixed, but a bit of manual testing shows that it seems to be working fine). I've just pushed it to the gallery.

**Comment by atzimler** [comment]
Thank you, seems to work perfectly.
