### ISSUE TITLE
Plugin seems to be ignored by ReSharper Command Line Tools

### ISSUE THREAD

**Issue by atzimler** [JetBrains/resharper-cyclomatic-complexity#11]
Hi,

I'm trying to use the plugin with the help of ReSharper Command Line Tools, but the output seems to be missing the Cyclomatic Complexity issues.

This is the command that I'm executing:
`C:\ReSharperCLT\inspectcode.exe -x=PowerToys.CyclomaticComplexity -o="report.xml" CodeDuplicates.sln`

The codebase, that I use to execute the command on, can be found at https://github.com/atzimler/CodeDuplicates.git .

I know for a fact that the VS R# with the plugin actually sees the issue, as I was using it during development of the example code.

Is there anything else that I'm missing or is this an issue?

Regards,
Attila

**Comment by matkoch** [comment]
Hi @atzimler,

the `-x` switch currently doesn't work. [Workarounds](https://youtrack.jetbrains.com/issue/RSRP-436208#comment=27-1667146) as well as the notification when it actually comes back, are tracked in the youtrack issue [RSRP-436208](https://youtrack.jetbrains.com/issue/RSRP-436208).

**Comment by atzimler** [comment]
Thanks, downloading the package into the installation directory of the Command Line Tool, switching on the plugin correctly.
