### ISSUE TITLE
R# 2017.1

### ISSUE THREAD

**Issue by atzimler** [JetBrains/resharper-cyclomatic-complexity#13]
Hi,

Is 2017.1 supported? The plugin does not seem to come up in the list of plugins able to install.

If I recall correctly, there was a similar issue with 2016.3, is there any way that I can help to solve this problem, so that I don't have to report it everytime Resharper is upgraded in version number?

Thanks,
Attila

**Comment by matkoch** [comment]
Hi Attila, it's already in the queue (#12).

**Comment by atzimler** [comment]
Thanks 👍 :)

**Comment by citizenmatt** [comment]
Now available in the Extension Manager!
