### ISSUE TITLE
Support for PhpStorm/WebStorm

### ISSUE THREAD

**Issue by pburrows** [JetBrains/resharper-cyclomatic-complexity#20]
Any chance of getting this plugin to work with WebStorm/PhpStorm (asked [here](https://plugins.jetbrains.com/plugin/10395-cyclomatic-complexity) too)?

Obviously not the C#, VB, and C++ bits. But the JavaScript and TypeScript support would be very useful in WebStorm / PhpStorm.

**Comment by matkoch** [comment]
Sorry, this is the wrong place. Can you please ask in https://youtrack.jetbrains.com/issues/WEB and https://youtrack.jetbrains.com/issues/WI ? This is a language plugin dependent feature.
