### ISSUE TITLE
Tooltip does not display

### ISSUE THREAD

**Issue by stevengopmo** [JetBrains/resharper-cyclomatic-complexity#21]
In previous versions mousing over the method showed the CC in a tooltip (as shown in your screenshots).  But for me, this no longer works.  Instead, it only shows in the status bar on the lower left-hand side and only when I click on the method vs. hover.  Is this something new from you or something wrong with my installation.

**Comment by matkoch** [comment]
It's an issue in ReSharper and there will probably be a fix in 2018.3.4.

I'm closing this already as there is no way to fix it on plugin side.

Thanks for reporting!
