### ISSUE TITLE
Incompatibility with Rider 2019.1.1

### ISSUE THREAD

**Issue by joaovieirabr** [JetBrains/resharper-cyclomatic-complexity#22]
After Rider's last update, just stoped working :(

<img width="850" alt="image" src="https://user-images.githubusercontent.com/2774195/57376503-83091180-7176-11e9-8cd9-66b67dd06639.png">

**Comment by matkoch** [comment]
Hi @joaovieirabr . I intentionally didn't publish it yet, did you see the [Cognitive Complexity plugin](https://github.com/matkoch/resharper-cognitivecomplexity)?

**Comment by joaovieirabr** [comment]
Thanks. I'm going to try it.

**Comment by joaovieirabr** [comment]
> Hi @joaovieirabr . I intentionally didn't publish it yet, did you see the [Cognitive Complexity plugin](https://github.com/matkoch/resharper-cognitivecomplexity)?

Do I have any intentions of updating it?

**Comment by shouwei** [comment]
@matkoch I asked exactly the same question here https://youtrack.jetbrains.com/issue/RSCPP-26345

I tried to search the Cognitive Complexity plugin, but it seems not available in 2019.1.1 yet.

**Comment by matkoch** [comment]
@joaovieirabr I also uploaded the cyclomatic complexity plugin now. I realized that it does support other languages too, as opposed to the cognitive complexity plugin, which currently only supports csharp.
