### ISSUE TITLE
Resharper 2019.1 - missing this plugin

### ISSUE THREAD

**Issue by robert-andrzejuk** [JetBrains/resharper-cyclomatic-complexity#23]
In Resharper Ultimate this plugin is missing from "Resharper Ultimate Extensions".

**Comment by matkoch** [comment]
It's published and should appear shortly. Still I want to link to another plugin, which implements a different metric, which should work better than Cyclomatic Complexity. It's available [here](https://github.com/matkoch/resharper-cognitivecomplexity), but only supports CSharp as of now.

**Comment by robert-andrzejuk** [comment]
@matkoch 
Thanks!

The other index is interesting and would like to try it out.
Unfortunatly I only use this on C++ code.

So I'll have to wait...
