### ISSUE TITLE
Conflicting reports of complexity

### ISSUE THREAD

**Issue by ghost** [JetBrains/resharper-cyclomatic-complexity#24]
![image](https://user-images.githubusercontent.com/30846057/73216206-2f32c400-411b-11ea-9bea-423e5f0d130e.png)

If the image uploaded correctly, you can see that it's showing both a complexity rating of 11 and a message saying it's too complex to analyze.  Is this an error or is it talking about two different types of complexity.  I started getting both of these after installing the plugin (2019.1.0) today.

Thanks,

Morgan

**Comment by matkoch** [comment]
The second message is actually from ReSharper and tells you that some code inspections won't run due to the complex body.
