### ISSUE TITLE
Webstorm support

### ISSUE THREAD

**Issue by michahell** [JetBrains/resharper-cyclomatic-complexity#25]
would be absolutely grand!

**Comment by matkoch** [comment]
Sorry, but WebStorm is out of scope of this project. You can create an issue on https://youtrack.jetbrains.com

**Comment by zhuravlikjb** [comment]
@michahell 
![image](https://user-images.githubusercontent.com/4499495/80813411-4675c780-8bca-11ea-9f0a-7a9299e723fd.png)
https://youtrack.jetbrains.com/issues/WEB for the issues, if you find any.

**Comment by michahell** [comment]
@zhuravlikjb thanks, I know, but it does not really work as well as codemetrics or this resharper plugin
