### ISSUE TITLE
No TypeScript and JavaScript options are listed in Rider Settings

### ISSUE THREAD

**Issue by AndrasJWork** [JetBrains/resharper-cyclomatic-complexity#26]
Hi,

In Rider, the TypeScript and JavaScript languages are not listed under the Settings unlike in the picture here -> https://github.com/JetBrains/resharper-cyclomatic-complexity/blob/master/docs/options.png

Print screen from my Rider Settings:
![image](https://user-images.githubusercontent.com/64948609/103414263-8cca5e80-4b7d-11eb-935b-5e8ed7afe182.png)

Could you please update the plugin to list these two languages as well?

Thank you!

Best regards,
András

**Comment by matkoch** [comment]
JS/TS in Rider is covered by our WebStorm implementation and not from ReSharper. So, unfortunately, as far as this plugin is concerned, we can't do anything.
