### ISSUE TITLE
Cannot build from clone

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-cyclomatic-complexity#28]
When cloning the project, the build will fail due to problems with the `ThemedIconConverter` task. It looks like this task requires msbuild 4.0, but the SDK based `.csproj` requires msbuild 15.0+

It's probably time to retire the XAML based icons and use SVGs instead.

**Comment by matkoch** [comment]
fixed in https://github.com/JetBrains/resharper-cyclomatic-complexity/commit/1bf0566357263361c0f8849f3f09f8f4f9ebc207
