### ISSUE TITLE
Update description for Rider

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-cyclomatic-complexity#29]
The Rider plugin uses the same description as the ReSharper plugin, which says it supports JavaScript and TypeScript. Rider uses WebStorm's web tooling, so does not support JS + TS.

**Comment by matkoch** [comment]
fixed in https://github.com/JetBrains/resharper-cyclomatic-complexity/commit/4d54b565fd35cb9a6d7096f2a4e115adb71ad6cb
