### ISSUE TITLE
Wrong calculation in C# hint

### ISSUE THREAD

**Issue by codingfreak** [JetBrains/resharper-cyclomatic-complexity#4]
In this screenshot

![strange](https://cloud.githubusercontent.com/assets/1045518/12085878/fdb66528-b2c4-11e5-8a07-9f8266a2cf58.png)

I get a hint that makes no sense to me. All settings are left at the default threshold of 20 and the message states that a threshold of 1 is 5% of 20 which is incorrect. What's the reson for this?

**Comment by citizenmatt** [comment]
The message is correct - 1 is 5% of 20.

**Comment by codingfreak** [comment]
Sorry! That wasn't my math-day obviously! Don't know what was wrong :-)
