### ISSUE TITLE
Show methods that exceed the cyclomatic-complexity in code issue inspection results

### ISSUE THREAD

**Issue by DavidArno** [JetBrains/resharper-cyclomatic-complexity#5]
Currently, for methods that exceed the cyclomatic-complexity threshold:
1. They are underlined with "squiggles",
2. They are indicated in the right-hand gutter within the editor (by default as a warning)
3. If the warning is changed to an error, they show up in the error list.

However, if not set as an error, they are hard to discover as they do not show up when eg, `Resharper->Inspect->Code issues in Solution` is selected. It would be a useful addition to this extension for them to do so, if possible.

**Comment by citizenmatt** [comment]
"Code Issues in Solution" is working for me:

<img width="535" alt="screen shot 2016-04-25 at 2 37 56 pm" src="https://cloud.githubusercontent.com/assets/222659/14785579/7395c726-0af3-11e6-8eb2-95c8845f5668.png">

 Do you have any other examples?

**Comment by citizenmatt** [comment]
Closing this issue for now. If you can still reproduce, please reopen.
