### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sheitmann** [JetBrains/resharper-cyclomatic-complexity#6]
Hi,

I get this error when I install the plugin or any other in R# 2016.1
`Loading an assembly “JetBrains.ReSharper.Resources, Version=105.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325” which is not listed in assembly references of assembly “JetBrains.ReSharper.Plugins.CyclomaticComplexity, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null” when trying to resolve the type JetBrains.ReSharper.Resources.Settings.CodeInspectionSettings. A type reference points into an assembly not listed among assembly references`

Any idea?

**Comment by derigel23** [comment]
https://youtrack.jetbrains.com/issue/RSRP-458452

**Comment by citizenmatt** [comment]
It's an issue with the installer - it's trying to load the plugin assembly to see if it has any custom install steps (it doesn't), and a validity check it's performing is throwing an error.

It can be safely ignored - it's installed fine.

(Some more detail: the code references the JetBrains.ReSharper.Resources assembly via a `typeof` expression in an attribute. Apparently, the compiler doesn't add an assembly reference for this, and the IoC container the installer uses sees the metadata, and expects the reference. I'll add a bit of code that forces a reference to be added, which should keep the container happy. I'll push an update later).
