### ISSUE TITLE
cyclomatic complexity full report

### ISSUE THREAD

**Issue by bootrider** [JetBrains/resharper-cyclomatic-complexity#8]
It is possible to have a full report of the cyclomatic complexity in a project?

**Comment by citizenmatt** [comment]
ReSharper doesn't really generate reports - it's more focussed on as-you-type information. The closest ReSharper has is the "Find similar issues" feature. Use <kbd>Alt</kbd>+<kbd>Enter</kbd> on a warning, and look in the submenu of "Inspection: Cyclomatic Complexity" (or similar wording) and then use "Find similar issues in file" or expand to find in project and solution. This will give you a list of other cyclomatic complexity warnings in a tree view, which has a toolbar button to export to XML or HTML.
