### ISSUE TITLE
Not available via Resharper extensions(v9.0.0)

### ISSUE THREAD

**Issue by suneeth** [JetBrains/resharper-cyclomatic-complexity#9]
couldn't find this extension for Resharper (v9.*) anymore.

**Comment by citizenmatt** [comment]
There actually wasn't a version for 9.0. You'll need to [install 9.1 or 9.2](https://resharper-support.jetbrains.com/hc/en-us/articles/207242355-Where-can-I-download-an-old-previous-ReSharper-version-) in order to get it (they're free upgrades if you have a license for 9.x)
